import importlib

try:
    BaseSettings = importlib.import_module("pydantic_settings").BaseSettings
except ModuleNotFoundError:  # Fallback for environments without pydantic-settings
    from pydantic.v1 import BaseSettings


class Settings(BaseSettings):
    """
    Application settings management with environment variables support
    """
    
    # Application
    APP_NAME: str = "ALIE - AI Lead Intelligence Engine"
    APP_VERSION: str = "1.0.0"
    ENVIRONMENT: str = "development"
    DEBUG: bool = True
    LOG_LEVEL: str = "INFO"
    
    # API
    API_V1_STR: str = "/api/v1"
    API_TITLE: str = "ALIE API"
    API_DESCRIPTION: str = "AI Lead Intelligence Engine for Local Business Recommendations"
    
    # Database
    NEO4J_URI: str = "bolt://localhost:7687"
    NEO4J_USER: str = "neo4j"
    NEO4J_PASSWORD: str = "password123"
    
    DATABASE_URL: str = "postgresql://alie_user:postgres123@localhost:5432/alie_db"
    DB_POOL_SIZE: int = 20
    DB_MAX_OVERFLOW: int = 0
    
    # Redis
    REDIS_URL: str = "redis://localhost:6379"
    REDIS_DB: int = 0
    REDIS_CACHE_TTL: int = 3600
    
    # Celery
    CELERY_BROKER_URL: str = "redis://localhost:6379/1"
    CELERY_RESULT_BACKEND: str = "redis://localhost:6379/2"
    
    # API Keys
    OPENAI_API_KEY: str = "your-openai-api-key"
    OPENAI_ASSISTANT_ID: str = ""  # Generated by register_openai_assistant.py
    TWOGIS_API_KEY: str = ""
    APIFY_TOKEN: str = ""
    GOOGLE_PLACES_KEY: str = ""
    
    # CORS
    CORS_ORIGINS: list = ["*"]
    CORS_ALLOW_CREDENTIALS: bool = True
    CORS_ALLOW_METHODS: list = ["*"]
    CORS_ALLOW_HEADERS: list = ["*"]
    
    # Data URLs
    CATALOG_BASE_URL: str = "https://ilyastas.github.io/katalog-ai"
    DATA_INDEX_URL: str = "https://ilyastas.github.io/katalog-ai/data/index.json"
    
    # Verification
    VERIFICATION_TIMEOUT: int = 30
    MAX_RETRIES: int = 3
    
    # Analytics
    TRACK_EVENTS: bool = True
    ANALYTICS_DB: str = "alie_db"
    ANALYTICS_TABLE: str = "lead_events"
    
    # Security
    SECRET_KEY: str = "your-super-secret-key-change-in-production"
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
    
    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        case_sensitive = True


# Global settings instance
settings = Settings()
