#!/usr/bin/env python3
"""
update_index.py — Auto-generates global-index.json from root company JSON files.

Scans root *.json files for valid company profiles
(id field must start with 'inst-' or 'brand-').

Usage:
    python scripts/update_index.py

Run before each commit after adding or modifying a company profile.
"""

import json
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUTPUT = ROOT / "global-index.json"
COMPANY_ID_RE = re.compile(r"^(inst-|brand-)")


def try_load_company(path: Path) -> dict | None:
    """Load a root JSON file and return an index entry if it is a valid company profile."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None
    if not isinstance(data, dict):
        return None
    company_id = data.get("id", "")
    if not COMPANY_ID_RE.match(str(company_id)):
        return None
    return {
        "id": company_id,
        "slug": data.get("slug", path.stem),
        "name": data.get("name", ""),
        "category": data.get("category", ""),
        "country": data.get("country", ""),
        "city": data.get("city", ""),
        "status": data.get("verification", {}).get("status", "unknown"),
        "file_path": f"/{path.name}",
        "profile_url": f"https://ilyastas.github.io/katalog-ai/{path.name}",
    }


def main() -> None:
    entries = [
        entry
        for path in sorted(ROOT.glob("*.json"))
        if (entry := try_load_company(path))
    ]

    index = {
        "version": "1.0.0",
        "updated_at": str(date.today()),
        "description": (
            "Lightweight map of all catalog entities for fast lookup by AI agents and crawlers. "
            "Auto-generated by scripts/update_index.py"
        ),
        "total": len(entries),
        "index": entries,
    }

    OUTPUT.write_text(json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"OK: global-index.json updated — {len(entries)} entries")


if __name__ == "__main__":
    main()
